### ISSUE TITLE
Allow partial model save

### ISSUE THREAD

**Issue by FynnBe** [kreshuklab/bioimg_rs#4]
to save incomplete work

**Comment by Tomaz-Vieira** [comment]
Done in version [v0.1.9](https://github.com/kreshuklab/bioimg_rs/releases/tag/v0.1.9)

**Comment by Tomaz-Vieira** [comment]
Done in version [v0.1.9](https://github.com/kreshuklab/bioimg_rs/releases/tag/v0.1.9)
